"""Templates for `ghostrun init` — a working first test in one command.

The point is time-to-first-success: install, run `ghostrun init`, run pytest,
see a passing test that replays instantly on the second run. No config authored
by hand, no reading the docs first.
"""

from __future__ import annotations

import importlib.util

CONFIG_TEMPLATE = """\
# ghostrun configuration. Generated by `ghostrun init` -- every value here is
# also a documented default; delete a line to fall back to it. Full reference:
# https://github.com/parthmax2/ghostrun/blob/main/doc/guide/configuration.md
mode: auto
cache_dir: .ghostrun_cache
judge:
  type: {judge_type}
  model: llama3.2:3b
  base_url: http://localhost:11434
"""

OPENAI_TEST_TEMPLATE = '''\
"""Generated by `ghostrun init`.

First run: records a real call to OpenAI and grades it (needs OPENAI_API_KEY
and, for the judge, `ollama pull llama3.2:3b`).
Every run after: replays from .ghostrun_cache/ -- no key, no network, no cost.

    pytest {filename}          # first run: records + grades for real
    pytest {filename}          # second run: instant, from cache

Edit the prompt or assertions below to fit your actual application, or replace
generate_reply() with a call into your own code.
"""
import ghostrun
from openai import OpenAI


def generate_reply(customer_message: str) -> str:
    client = OpenAI()  # reads OPENAI_API_KEY from the environment
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {{"role": "system", "content": "You are an empathetic support agent."}},
            {{"role": "user", "content": customer_message}},
        ],
    )
    return resp.choices[0].message.content


@ghostrun.record(model="gpt-4o-mini")
def test_reply_is_empathetic():
    reply = generate_reply("Where is my refund? It's been three weeks.")

    ghostrun.expect(reply).contains_intent("apology")
    ghostrun.expect(reply).tone_is("empathetic")
'''

ANTHROPIC_TEST_TEMPLATE = '''\
"""Generated by `ghostrun init`.

First run: records a real call to Anthropic and grades it (needs
ANTHROPIC_API_KEY and, for the judge, `ollama pull llama3.2:3b`).
Every run after: replays from .ghostrun_cache/ -- no key, no network, no cost.

    pytest {filename}          # first run: records + grades for real
    pytest {filename}          # second run: instant, from cache

Edit the prompt or assertions below to fit your actual application, or replace
generate_reply() with a call into your own code.
"""
import ghostrun
import anthropic


def generate_reply(customer_message: str) -> str:
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from the environment
    resp = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=300,
        system="You are an empathetic support agent.",
        messages=[{{"role": "user", "content": customer_message}}],
    )
    return resp.content[0].text


@ghostrun.record(model="claude-haiku-4-5-20251001")
def test_reply_is_empathetic():
    reply = generate_reply("Where is my refund? It's been three weeks.")

    ghostrun.expect(reply).contains_intent("apology")
    ghostrun.expect(reply).tone_is("empathetic")
'''

GENERIC_TEST_TEMPLATE = '''\
"""Generated by `ghostrun init`.

No OpenAI or Anthropic SDK was detected, so this test calls a provider
directly over HTTP -- swap in your own app's function instead of
generate_reply(). ghostrun intercepts at the HTTP layer, so it works
transparently regardless of which SDK (or none) your code uses.

    pytest {filename}          # first run: records + grades for real
    pytest {filename}          # second run: instant, from cache
"""
import os

import httpx

import ghostrun


def generate_reply(customer_message: str) -> str:
    resp = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={{"Authorization": f"Bearer {{os.environ['OPENAI_API_KEY']}}"}},
        json={{
            "model": "gpt-4o-mini",
            "messages": [
                {{"role": "system", "content": "You are an empathetic support agent."}},
                {{"role": "user", "content": customer_message}},
            ],
        }},
    )
    return resp.json()["choices"][0]["message"]["content"]


@ghostrun.record(model="gpt-4o-mini")
def test_reply_is_empathetic():
    reply = generate_reply("Where is my refund? It's been three weeks.")

    ghostrun.expect(reply).contains_intent("apology")
    ghostrun.expect(reply).tone_is("empathetic")
'''


def detect_sdk() -> str:
    """Returns 'openai', 'anthropic', or 'generic' based on what's importable."""
    if importlib.util.find_spec("openai") is not None:
        return "openai"
    if importlib.util.find_spec("anthropic") is not None:
        return "anthropic"
    return "generic"


def render_test_file(sdk: str, filename: str) -> str:
    template = {
        "openai": OPENAI_TEST_TEMPLATE,
        "anthropic": ANTHROPIC_TEST_TEMPLATE,
        "generic": GENERIC_TEST_TEMPLATE,
    }[sdk]
    return template.format(filename=filename)


def render_config(judge_type: str = "ollama") -> str:
    return CONFIG_TEMPLATE.format(judge_type=judge_type)
